# Generated by Django 3.2.19 on 2023-07-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_id',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.group'),
            preserve_default=False,
        ),
    ]
