# Generated by Django 3.2.19 on 2023-07-13 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230710_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='featuredImage',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
