# Generated by Django 3.2.19 on 2023-07-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_group_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
